.PHONY: clean All

All:
	@echo "----------Building project:[ Question7 - Debug ]----------"
	@$(MAKE) -f  "Question7.mk"
clean:
	@echo "----------Cleaning project:[ Question7 - Debug ]----------"
	@$(MAKE) -f  "Question7.mk" clean
