.PHONY: clean All

All:
	@echo "----------Building project:[ question7 - Debug ]----------"
	@$(MAKE) -f  "question7.mk"
clean:
	@echo "----------Cleaning project:[ question7 - Debug ]----------"
	@$(MAKE) -f  "question7.mk" clean
