.PHONY: clean All

All:
	@echo "----------Building project:[ question5 - Debug ]----------"
	@$(MAKE) -f  "question5.mk"
clean:
	@echo "----------Cleaning project:[ question5 - Debug ]----------"
	@$(MAKE) -f  "question5.mk" clean
