.PHONY: clean All

All:
	@echo "----------Building project:[ question6 - Debug ]----------"
	@$(MAKE) -f  "question6.mk"
clean:
	@echo "----------Cleaning project:[ question6 - Debug ]----------"
	@$(MAKE) -f  "question6.mk" clean
