.PHONY: clean All

All:
	@echo "----------Building project:[ question3 - Debug ]----------"
	@$(MAKE) -f  "question3.mk"
clean:
	@echo "----------Cleaning project:[ question3 - Debug ]----------"
	@$(MAKE) -f  "question3.mk" clean
